monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log" 
            level: error
            # action_level: error
            # handler: nested
            # excluded_http_codes: [404, 405]
            # buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            max_files: 10
        # this seems to be ignored. only config above works
        # nested:
            # type: rotating_file
            # this does not work with nginx - no errors are logged to error log
            # path: php://stderr             
            # path: "%kernel.logs_dir%/%kernel.environment%.log"            
            # level: info
            # formatter: monolog.formatter.json
            # max_files: 10
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

                        